language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t fq600/docker-travisci-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fq600/docker-travisci-react npm run test -- --coverage
